version: "3"

services:
  api:
    image: dochugoker/mmserver
    # build:
    #   context: ./server
    #   dockerfile: dev.dockerfile
    ports:
      - 4000:4000
    environment:
      - JWT_SECRET=supersecretcode
    command: npm run start
    volumes:
      - ./server/src:/mastermine/dev/server/src
      - ./server/ormconfig.json:/mastermine/dev/server/ormconfig.json
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mastermine
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
