version: "3"

services:
  server:
    image: dochugoker/mmserver
    build:
      context: ./server
      dockerfile: dev.dockerfile
    ports:
      - 4000:4000
    command: npm start
    volumes:
      - ./server/src/:/app/src
