version: "3"

services:
  api:
    image: dochugoker/mmserver
    build:
      context: ./server
      dockerfile: prod.dockerfile
    ports:
      - 4000:4000
    command: npm start
    # volumes:
    #   - ./server/dist/:/app/dist
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mastermine
    volumes:
      - mydb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mydb:
