name: docker-ci

on:
  # push:
  # branches:
  # - "main"
  # tags:
  #   - 'v*'
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} #username de l'hôte
          password: ${{ secrets.DOCKERHUB_TOKEN }} #Token de l'hôte
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/dev.dockerfile
          push: true
          tags: dochugoker/mmserver:latest #changer par le tag de l'hôte
          # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mastermine:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mastermine:buildcache,mode=max
